[package]
name = "detta-consensus"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = []
experimental-da = ["detta-core/experimental-da", "detta-da/experimental-da"]

[dependencies]
detta-core = { path = "../detta-core" }
detta-da = { path = "../detta-da" }
serde = { version = "1.0", features = ["derive"] }
