[workspace]
members = [
    "crates/detta-core",
    "crates/detta-rpc",
    "crates/detta-verify",
    "crates/detta-consensus",
    "crates/detta-storage",
    "crates/detta-evaluator",
    "crates/detta-node",
    "crates/detta-network",
    "crates/detta-protocol",
    "crates/detta-e2e",
]
resolver = "2"
