[package]
name = "detta-network"
version = "0.1.0"
edition = "2021"
license = "MIT"

[features]
default = []
experimental-da = [
    "detta-consensus/experimental-da",
    "detta-core/experimental-da",
    "detta-protocol/experimental-da",
]

[dependencies]
detta-consensus = { path = "../detta-consensus" }
detta-core = { path = "../detta-core" }
detta-protocol = { path = "../detta-protocol" }
serde = { version = "1.0", features = ["derive"] }
