[package]
name = "detta-node"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
detta-consensus = { path = "../detta-consensus" }
detta-core = { path = "../detta-core" }
detta-network = { path = "../detta-network" }
detta-rpc = { path = "../detta-rpc" }
detta-storage = { path = "../detta-storage" }
